name: Build Skia on Update

on:
  schedule:
    - cron: '0 * * * *'  # Runs hourly
  workflow_dispatch:
  push:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Import variable
        uses: UnlyEd/github-action-store-variable@v3 # See https://github.com/UnlyEd/github-action-store-variable
        with:
          # List all variables you want to retrieve from the store
          # XXX They'll be automatically added to your ENV
          variables: |
            LAST_COMMIT_HASH
            
      - name: Clone Skia repo
        run: |
          git clone --depth 1 https://github.com/google/skia.git
          cd skia
          echo "LAST_COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV
      
      - name: Compare with last commit hash
        if: env.latest_commit != ${{ env.LAST_COMMIT_HASH }}
        run: |
          echo "New commit found: Building Skia..."
          # Add build steps here, such as `./tools/build_script`
      
      - name: Release binaries
        if: success()
        run: |
          # Add steps to release binaries here

      - name: Export variables for next jobs
        uses: UnlyEd/github-action-store-variable@v3 # See https://github.com/UnlyEd/github-action-store-variable
        with:
          variables: |
            LAST_COMMIT_HASH=${{ env.LAST_COMMIT_HASH }}
