name: Build Skia on Update

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily
  workflow_dispatch:
  push:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Skia repo
        run: |
          git clone --depth 1 https://github.com/google/skia.git
          cd skia
      
      - name: Fetch dependencies
        run: python3 tools/git-sync-deps && python3 bin/fetch-ninja && python3 bin/fetch-gn

      - name: Configure Skia
        run: bin/gn gen out/Shared --args='ar = "ar" extra_cflags = ["-ffunction-sections", "-fdata-sections", "-fno-rtti", "-Wl,--gc-sections", "-flto", "-Oz"] is_component_build=true is_debug=false is_official_build=true paragraph_gms_enabled=false paragraph_tests_enabled=false skia_canvaskit_enable_alias_font=false skia_canvaskit_enable_canvas_bindings=false skia_canvaskit_enable_effects_deserialization=false skia_canvaskit_enable_embedded_font=false skia_canvaskit_enable_font=false skia_canvaskit_enable_paragraph=false skia_canvaskit_enable_pathops=false skia_enable_bentleyottmann=true skia_enable_fontmgr_android=false skia_canvaskit_enable_pathops=false skia_use_dng_sdk=false skia_enable_fontmgr_custom_empty=false skia_enable_skottie=true skia_enable_pdf=false skia_enable_skparagraph=true skia_enable_skshaper=true skia_enable_skshaper_tests=false skia_enable_api_available_macro=false skia_compile_modules=true skia_enable_svg=true skia_use_dng_sdk=false skia_use_egl=true skia_use_expat=false skia_use_icu=false skia_use_perfetto=false skia_use_piex=false skia_use_system_expat=false skia_use_system_icu=false skia_use_wuffs=false skia_use_x11=false skia_use_xps=false'

      - name: Build
        run: ninja -C out/Shared
      
      - name: Release binaries
        if: success()
        run: |
          # Add steps to release binaries here

      - name: Upload File
        uses: actions/upload-artifact@v4
        with:
          name: env
          path: env.sh
