name: Build Skia on Update

on:
  schedule:
    - cron: '0 * * * *'  # Runs hourly
  workflow_dispatch:
  push:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Download File
        uses: actions/download-artifact@v4
        with:
          name: env

      - name: Import env
        run: ./env.sh
        continue-on-error: true
          
      - name: Clone Skia repo
        run: |
          git clone --depth 1 https://github.com/google/skia.git
          cd skia
          echo "latest_commit=$(git rev-parse HEAD)" >> $GITHUB_ENV
      
      - name: Compare with last commit hash
        if: env.latest_commit != ${{ env.LAST_COMMIT_HASH }}
        run: |
          echo "New commit found: Building Skia..."
          # Add build steps here, such as `./tools/build_script`
          echo "echo LAST_COMMIT_HASH=$latest_commit >> $GITHUB_ENV" >> env.sh
          ./env.sh
      
      - name: Release binaries
        if: success()
        run: |
          # Add steps to release binaries here

      - name: Upload File
        uses: actions/upload-artifact@v4
        with:
          name: env
          path: env.sh
